### ISSUE TITLE
Tooltip persists after sudden focus change

### ISSUE THREAD

**Issue by Felix14-v2** [EZForever/ThatOrThis#14] opened 2021-06-28 22:32 UTC
It is funny, but it is a bug :)
[Demo](https://youtu.be/aUt5ZQqHgkc)
(I used a laptop touchpad to get this)

[my rules – rules.zip](https://github.com/EZForever/ThatOrThis/files/6729566/rules.zip)

**Comment by EZForever** [comment] 2021-06-29 18:05
This bug is funny indeed, however I can't reproduce it with your rules.json, whether with a touchpad or a mouse.

From your video it seems that, if a tooltip is displaying, and the button providing it just scroll out of view, the tooltip will refuse to disappear. Is this understanding correct?

Also, please try to reproduce the bug without any mods other than those ThatOrThis depends on.

**Comment by Felix14-v2** [comment] 2021-06-30 10:42
> button providing it just scroll out of view, the tooltip will refuse to disappear
Absolutely right.

I disabled all mods (deleted the files and disabled them), but the situation remained the same: 
https://youtu.be/TZeGjirvktM
https://youtu.be/ZVQhFWa7j7c

**Comment by EZForever** [comment] 2021-06-30 15:24
OK I've managed to reproduce the bug, but in a different procedure:

1. Open ThatOrThis menu;
2. Select an option by pressing TAB on keyboard, the tooltip will appear around mouse cursor;
3. Move cursor away or to another option, erratic behavior begins.

My guess is that, by using a touchpad (or maybe *some* touchpads, as mine works fine) some kind of implied keyboard focus is applied onto the option button. Then the cause of problems surfaced: Minecraft treats keyboard focus the same as mouse hovering (`net.minecraft.client.gui.widget.ClickableWidget#isHovered`), so there can be at most two buttons in a "hovered" state, causing chaos. I'm working on a fix.

**Comment by EZForever** [comment] 2021-07-01 03:56
Try this snapshot: [thatorthis-0.2.4+1.17@9318c55.jar.zip](https://github.com/EZForever/ThatOrThis/files/6745261/thatorthis-0.2.4%2B1.17%409318c55.jar.zip) (unzip before installing). Tooltips for keyboard focused buttons are now not shown. Mouse hovering works as normal.

**Comment by Felix14-v2** [comment] 2021-07-01 23:21
The result remained the same. However, I do not think that such a small feature is worth so much attention if it is so difficult to detect. If you want, you can close this issue.

By the way, I think this is a simple solution to add small delay after hovering over the button to display the tooltip.

**Comment by EZForever** [comment] 2021-07-01 23:51
Frankly I don't know what else could go wrong with these tooltips... can't even confirm whether the problem is on my side or not. I'll keep this issue open, but further investgation can't be done without some help.

**Comment by EZForever** [comment] 2021-07-01 23:52
Frankly I don't know what else could go wrong with these tooltips... can't even confirm whether the problem is on my side or not. I'll keep this issue open, but further investgation can't be done without some help.

**Comment by EZForever** [comment] 2021-07-21 14:56
Okay, maybe by checking mouse poisition against list entries instead of desynchronized button coordinates, we can "force" the tooltip to show only when wanted. Try this snapshot: [thatorthis-0.2.4+1.17@b53938e.jar.zip](https://github.com/EZForever/ThatOrThis/files/6856707/thatorthis-0.2.4%2B1.17%40b53938e.jar.zip) (unzip before installing).

**Comment by Felix14-v2** [comment] 2021-07-23 10:27
Now tooltip works as it should 👍

**Comment by EZForever** [comment] 2021-08-02 07:34
[v0.2.5+1.17](https://github.com/EZForever/ThatOrThis/releases/tag/v0.2.5%2B1.17) is out, containing the fix. Closing this issue.

**Closed by EZForever** 2021-08-02 07:34 UTC
Labels: bug
